### ISSUE TITLE
Incorrect Jordan Wigner transform

### ISSUE THREAD

**Issue by christopherkang** [MicrosoftDocs/quantum-docs-pr#507]
[Enter feedback here]
In the transformation from the creation operator to its Pauli equivalent, the summation doesn't actually equal the given matrix. Similarly, the annihilation operator doesn't equal it's Pauli equivalent. The actual formulas are used later on in the text, but the first mention is incorrect: 

<img width="493" alt="Screen Shot 2019-09-03 at 10 53 16 AM" src="https://user-images.githubusercontent.com/42285636/64196596-0d1d6a00-ce39-11e9-89fa-b04946cddfd7.png">

(also, if possible, the spacing should be fixed)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de4f0bcf-e335-8173-6761-d3440f84db82
* Version Independent ID: 98d49390-a026-46ce-2886-19969fe24224
* Content: [Jordan-Wigner Representation](https://docs.microsoft.com/en-us/quantum/libraries/chemistry/concepts/jordan-wigner?view=qsharp-preview)
* Content Source: [articles/libraries/chemistry/concepts/jordan-wigner.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/chemistry/concepts/jordan-wigner.md)
* Product: **quantum**
* GitHub Login: @nathanwiebe2
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by cgranade** [comment]
Thanks for pointing this out! It looks like somehow 𝑎ⱼ⁺ and 𝑎ⱼ got swapped with each other (ironically). The spacing issue seems to be because `\\\` was used instead of `\\\\` as is required for MathJax to see a `\\` through the Markdown processor.

**Comment by cgranade** [comment]
Closing, as this has been addressed with #513. Please feel free to reopen if needed, or to file another issue with follow-ups. Thanks for the report!

**Comment by christopherkang** [comment]
#513 is still broken - switching the matrix forms was incorrect. Here are the final formulas

![image](https://user-images.githubusercontent.com/42285636/64460270-d2bd0280-d0ae-11e9-9f07-ca724dd43015.png)

Additionally, the line before describing the annihilation / creation operators has an error. Those formulas are also provided.

**Comment by christopherkang** [comment]
Current: 
![image](https://user-images.githubusercontent.com/42285636/64460402-2891aa80-d0af-11e9-8ea7-834d92d6f884.png)

**Comment by cgranade** [comment]
That's very odd, it looked right in the preview, will investigate. Thanks for the heads-up!

**Comment by geduardo** [comment]
Ok, this is a bit weird. Most references I found use the current form (1. http://home.uchicago.edu/dtson/phys411/Jordan-Wigner.pdf, 2. https://www.lptmc.jussieu.fr/user/messio/ICFP_documents/TD_Jordan_Wigner_enonce.pdf and 3. https://en.wikipedia.org/wiki/Jordan–Wigner_transformation). However, going to the original paper they use a different representation of Pauli matrices, but doing the explicit calculation gives the matrices provided by @christopherkang, which are the ones that make sense for them to be creation and annihilation operators (assuming we are using the cartesian basis |0>=(1,0)^T and |1>=(0,1)^T).
I think the discrepancy has to do with the chosen cartesian basis for up and down, but not completely sure.

**Comment by christopherkang** [comment]
@geduardo I think you're right! Let's look at the matrix form of the z spin operator they define:

![image](https://user-images.githubusercontent.com/42285636/64550604-1d758f00-d2e8-11e9-8bf6-5a1a55bd1dfd.png)

Now, we can analyze it's behavior by putting in spin up / spin down kets and comparing it to the expected result.

If we put in spin up, we should get half spin up back. If we put in spin down, we should get negative half spin down:

![image](https://user-images.githubusercontent.com/42285636/64550829-9674e680-d2e8-11e9-994a-e20738bec52f.png)

So, we are looking for two eigenvectors with eigenvalues of 1 and 0, meaning that spin up is the 0 ket, and spin down is the 1 ket. (I guess because 0 is 'above' the 1?)

**Comment by guanghaolow** [comment]
@christopherkang @cgranade @geduardo Thanks for identifying this inconsistency.

This issue is caused by a difference in convention between Q#'s representation of the |0> state and the |0> state in some areas of physics.

Q# represents |0> as the +1 eigenstate of the Z operator.
In some areas of physics, |0> is the low-energy ground state, thus the -1 eigenstate of the Z operator.

The correct version is in @christopherkang 's image:

> ![image](https://user-images.githubusercontent.com/42285636/64460270-d2bd0280-d0ae-11e9-9f07-ca724dd43015.png)

To see why, the following are assertions that the fermionic creation operator must satisfy.
1) In the chemistry library, we use |0> to represent an unoccupied spin-orbital, and |1> to represent an occupied spin-orbitals.
2) Thus a raising operator should be a^\dagger = |1><0|.

The following is the Q# convention for what a |0> state is.
3) Q# represents the |0> state as the +1 eigenstate of the Z operator (in Q#, this is the value of Zero of the Result type). Thus the Z operator = |0><0| - |1><1|
4) The Z operator in matrix form is written as 1st row: (1,0); 2nd row: (0,-1). Thus |0> as a column vector is 1st row:(1); 2nd row:(0).
5) Thus a^\dagger = |1><0| is as shown in Chris' image.

**Comment by geduardo** [comment]
@christopherkang @cgranade @guanghaolow 
Great! That's what I was thinking. Thanks for the clarification! I'll try to fix it asap.
